# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
# fastlane_version "2.210.1"

default_platform :ios

platform :ios do
  lane :test_flight do
    # "Q58Q4Y9A5W"
    key_id = ENV["KEY_ID"]
    puts "FASTLANE KEY_ID: #{key_id}"
    # "69a6de95-7865-47e3-e053-5b8c7c11a4d1"
    issuer_id = ENV["ISSUER_ID"]
    puts "FASTLANE ISSUER_ID: #{issuer_id}"
    # ../../build/ios/ipa/Апетка Ригла.ipa
    ipa_path = ENV["IPA_PATH"]
    puts "FASTLANE IPA_PATH: #{ipa_path}"
    # ../../ios/certs/AuthKey_Q58Q4Y9A5W.p8
    p8_path = ENV["P8_PATH"]
    puts "FASTLANE P8_PATH: #{p8_path}"

    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_filepath: p8_path,
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
  
    upload_to_testflight(
      api_key: api_key,
      skip_submission: true,
      ipa: ipa_path,
      skip_waiting_for_build_processing: true,
      changelog: 'Try to get this info from Github tag',
    )
  end

  lane :firebase do
    app_id = ENV["APP_ID"]
    groups = ENV["GROUPS"]
    firebase_cli_token = ENV["FIREBASE_TOKEN"]
    ipa_path = ENV["IPA_PATH"]
    puts "FASTLANE APP_ID: #{app_id}"
    puts "FASTLANE GROUPS: #{groups}"
    puts "FASTLANE FIREBASE_TOKEN: #{firebase_cli_token}"
    puts "FASTLANE IPA_PATH: #{ipa_path}"
    puts "Firebase App Distribution"
    upload_to_fad(
      app_id: app_id,
      ipa_path: ipa_path,
      groups: groups,
      firebase_cli_token: firebase_cli_token,
      release_notes: "TODO: Get from Github tag release note",
   )
  end
    lane :upload_to_fad do |options|
    app_id = options[:app_id]
    ipa_path = options[:ipa_path]
    groups = options[:groups]
    release_notes = options[:release_notes]
    firebase_cli_token = options[:firebase_cli_token]
    firebase_app_distribution(
        app: "#{app_id}",
        ipa_path: "#{ipa_path}",
        groups: "#{groups}",
        release_notes: "#{release_notes}",
        firebase_cli_token: "#{firebase_cli_token}",
      )
   end
end
