# Конфигурация Fastlane для Android-сборки.
#
# ВАЖНО: в релизном цикле Android-сборки Fastlane используется только для CD (выгрузка приложения в
# Firebase App Distribution).
#
# Документация:https://docs.fastlane.tools

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_version "2.210.1"
firebase_app_id = <FIREBASE_APP_ID> # TODO: Add firebase app id in double quotes

default_platform(:android)

platform :android do

  desc "Submit a new debug build to Firebase App Distribution"
  lane :beta do do |options|
    app_id = options[:app_id]
    groups = options[:groups]
    puts "#{app_id}"
    puts "#{groups}"
  puts "Firebase App Distribution | QA Build"
  upload_to_fad(
      app_id: app_id,
      apk_path: "../build/app/outputs/flutter-apk/app-dev-release.apk",
      groups: groups,
      release_notes: "QA",
   )

  # puts "Firebase App Distribution | QA Build | 64-bit"
  # upload_to_fad(
  #     app_id: firebase_app_id,
  #     apk_path: "../build/app/outputs/apk/dev/release/app-qa-arm64-v8a.apk",
  #     groups: "Surf",
  #     release_notes: "QA x64",
  # )
  end

  lane :upload_to_fad do |options|
    app_id = options[:app_id]
    apk_path = options[:apk_path]
    groups = options[:groups]
    release_notes = options[:release_notes]
    firebase_app_distribution(
        app: "#{app_id}",
        apk_path: "#{apk_path}",
        groups: "#{groups}",
        release_notes: "#{release_notes}",
        firebase_cli_path: "/usr/local/bin/firebase",
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
      )
   end
end
