# Конфигурация Fastlane для Android-сборки.
#
# ВАЖНО: в релизном цикле Android-сборки Fastlane используется только для CD (выгрузка приложения в
# Firebase App Distribution).
#
# Документация:https://docs.fastlane.tools

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# fastlane_version "2.212.1"
# firebase_app_id = <FIREBASE_APP_ID> # TODO: Add firebase app id in double quotes

default_platform(:android)

platform :android do

  desc "Submit a new debug build to Firebase App Distribution"
  lane :firebase do
    app_id = ENV["APP_ID"]
    groups = ENV["GROUPS"]
    firebase_cli_token = ENV["FIREBASE_TOKEN"]
    apk_path = ENV["APK_PATH"]
    puts "FASTLANE APP_ID: #{app_id}"
    puts "FASTLANE GROUPS: #{groups}"
    puts "FASTLANE FIREBASE_TOKEN: #{firebase_cli_token}"
    puts "FASTLANE APK_PATH: #{apk_path}"
    puts "Firebase App Distribution"
    upload_to_fad(
      app_id: app_id,
      apk_path: apk_path,
      groups: groups,
      firebase_cli_token: firebase_cli_token,
      release_notes: "TODO: Get from Github tag release note",
   )
  end
    lane :upload_to_fad do |options|
    app_id = options[:app_id]
    apk_path = options[:apk_path]
    groups = options[:groups]
    release_notes = options[:release_notes]
    firebase_cli_token = options[:firebase_cli_token]
    firebase_app_distribution(
        app: "#{app_id}",
        apk_path: "#{apk_path}",
        groups: "#{groups}",
        release_notes: "#{release_notes}",
        firebase_cli_token: "#{firebase_cli_token}",
      )
   end

  lane :google_play do
    aab_path = ENV["AAB_PATH"]
    package_name = ENV["PKG_NAME"]
    json_path = ENV["JSON_PATH"]
    puts "FASTLANE AAB_PATH: #{aab_path}"
    puts "FASTLANE PACKAGE_NAME: #{package_name}"
    puts "FASTLANE JSON PATH: #{json_path}"
    puts "Google Play Console"
    # Call 'fastlane action upload_to_play_store' for more information.
    upload_to_play_store(
      package_name: "#{package_name}",
      track: "internal",
      json_key: "#{json_path}",
      aab: "#{aab_path}",
    )
  end
end
